"""add_device_rotation_fields

Revision ID: a33244dc6329
Revises: c735830ffa3e
Create Date: 2026-09-14 02:35:02.188959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33244dc6329'
down_revision: Union[str, Sequence[str], None] = 'c735830ffa3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sim_count', sa.Integer(), server_default='2', nullable=False))
        batch_op.add_column(sa.Column('last_sim_slot', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('total_sent_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('hourly_sent_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('max_hourly_per_sim', sa.Integer(), server_default='30', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('max_hourly_per_sim')
        batch_op.drop_column('hourly_sent_count')
        batch_op.drop_column('total_sent_count')
        batch_op.drop_column('last_sim_slot')
        batch_op.drop_column('sim_count')

    # ### end Alembic commands ###
