"""add_sms_templates

Revision ID: c735830ffa3e
Revises: aba2b7e40845
Create Date: 2026-09-14 02:27:08.568304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c735830ffa3e'
down_revision: Union[str, Sequence[str], None] = 'aba2b7e40845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_templates_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_templates_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_templates_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_templates_is_active'))
        batch_op.drop_index(batch_op.f('ix_sms_templates_id'))
        batch_op.drop_index(batch_op.f('ix_sms_templates_category'))

    op.drop_table('sms_templates')
    # ### end Alembic commands ###
