"""add_blacklisted_phones

Revision ID: dc233a7e5221
Revises: a33244dc6329
Create Date: 2026-09-15 02:36:41.184264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc233a7e5221'
down_revision: Union[str, Sequence[str], None] = 'a33244dc6329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklisted_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklisted_phones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklisted_phones_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_blacklisted_phones_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklisted_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklisted_phones_phone_number'))
        batch_op.drop_index(batch_op.f('ix_blacklisted_phones_is_active'))
        batch_op.drop_index(batch_op.f('ix_blacklisted_phones_id'))

    op.drop_table('blacklisted_phones')
    # ### end Alembic commands ###
